version: "3.7"
services:
  go-poker:
    container_name: go-poker
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis

  redis:
    container_name: go-poker-redis
    image: redis:latest
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  redis:
