services:
  postgres:
    container_name: go-poker-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-poker_platform}
      POSTGRES_USER: ${POSTGRES_USER:-poker_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-poker_password}
      # Additional databases for Formance
      POSTGRES_MULTIPLE_DATABASES: ledger
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-poker_user} -d ${POSTGRES_DB:-poker_platform}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ledger:
    image: "ghcr.io/formancehq/ledger:v2.2.0"
    container_name: go-poker-ledger
    restart: unless-stopped
    ports:
      - "3068:3068"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3068/_healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URI: "postgresql://ledger:${POSTGRES_PASSWORD:-poker_password}@postgres:5432/ledger?sslmode=disable"

  redis:
    container_name: go-poker-redis
    image: redis:latest
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
  redis_data:
